import numpy as np
import rasterio

# Path to the delta raster generated by your scenario script
delta_path = "results_greening_hamburg_rf_tuned/delta_LST.tif"

with rasterio.open(delta_path) as src:
    delta = src.read(1)
    # Calculate mean ignoring NaNs (areas outside city/mask)
    mean_change = np.nanmean(delta)

print(f"City-Wide Mean LST Decrease: {-mean_change:.4f} °C")